config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :planets, only: [:show] do
    resources :aliens, only: [:new, :create]
  end
  resources :aliens, only: [:destroy] do
    resources :holsters, only: [:new, :create]
  end
end


# As as user, I can give an alien a weapon
# holsters#new/create
# get 'aliens/:alien_id/holsters/new'
# post 'aliens/:alien_id/holsters'

app/models/alien.rb
class Alien < ApplicationRecord
  belongs_to :planet
  has_many :holsters, dependent: :destroy
  has_many :weapons, through: :holsters
  validates :name, presence: true
  has_one_attached :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/holster.rb
class Holster < ApplicationRecord
  belongs_to :alien # holster.alien
  belongs_to :weapon # holster.weapon
  # validates :alien, uniqueness: { scope: :weapon }
  validates :weapon, uniqueness: { scope: :alien }
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :aliens, dependent: :destroy # planet.aliens
  validates :name, presence: true
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :holsters # weapon.holsters
  has_many :aliens, through: :holsters # weapon.aliens
  has_many :planets, through: :aliens # weapon.planets
  validates :name, presence: true, uniqueness: true
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController

  # '/planets/1/aliens/new'
  def new
    @alien = Alien.new
    @planet = Planet.find(params[:planet_id])
  end

  # post '/planets/1/aliens' (from the form)
  def create
    @planet = Planet.find(params[:planet_id]) # loading nested resource first
    @alien = Alien.new(alien_params)
    @alien.planet = @planet # giving the reference to the alien
    if @alien.save
      redirect_to planet_path(@planet)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @alien = Alien.find(params[:id])
    @alien.destroy
    redirect_to planet_path(@alien.planet), status: :see_other
  end

  private

  def alien_params
    params.require(:alien).permit(:name, :photo, :species)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/holsters_controller.rb
class HolstersController < ApplicationController

  # 'aliens/:alien_id/holsters/new'
  def new
    @holster = Holster.new
    @alien = Alien.find(params[:alien_id])
    # @weapons = Weapon.order(name: :asc)
    # @weapons = @alien.weapons
    @weapons = Weapon.where.not(id: @alien.weapons).order(name: :asc)
  end

  def create
    @alien = Alien.find(params[:alien_id])
    @holster = Holster.new(holster_params)
    @holster.alien = @alien
    if @holster.save
      redirect_to planet_path(@alien.planet)
    else
      @weapons = Weapon.where.not(id: @alien.weapons).order(name: :asc)
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def holster_params
    params.require(:holster).permit(:weapon_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @planets = Planet.all
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  # '/planets/:id'
  def show
    @planet = Planet.find(params[:id])
  end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holsters_helper.rb
module HolstersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/aliens/new.html.erb
<div class="container">
  <h1>Welcome a new Alien to <%= @planet.name %></h1>
  <%= simple_form_for [@planet, @alien] do |f| %>
    <%= f.input :name %>
    <%#= f.input :image_url %>
    <%= f.input :photo, as: :file %>
    <%= f.input :species %>
    <%= f.submit class: 'btn btn-success mt-2' %>
  <% end %>
</div>

app/views/holsters/new.html.erb
<div class="container">
  <h1>Add a Weapon to <%= @alien.name %></h1>
  <%= simple_form_for [@alien, @holster] do |f| %>
    <%= f.association :weapon, collection: @weapons, include_blank: false %>
    <%= f.submit 'Add', class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarOfWorlds</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://d18lkz4dllo6v2.cloudfront.net/cumulus_uploads/entry/43959/adobe-aliens.jpeg);">
  <div class="container">
    <h1>War of Worlds</h1>
  </div>
</div>
<div class="container my-5">
  <div class="cards">
    <% @planets.each do |planet| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= planet.banner_url %>)">
        <%= planet.name %>
        <%= link_to '', planet_path(planet), class: 'card-category-link'%>
      </div>
    <% end %>
  </div>
</div>

app/views/planets/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @planet.banner_url %>);">
  <div class="container">
    <h1><%= @planet.name %></h1>
    <p>Change your life, come to <%= @planet.name %>.</p>
    <%= link_to 'Add Alien', new_planet_alien_path(@planet), class: 'btn btn-success'  %>
  </div>
</div>
<div class="container my-3">
  <!-- TODO: put aliens here -->
  <div class="cards">
    <% @planet.aliens.each do |alien| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= alien.photo.attached? ? cl_image_path(alien.photo.key) : alien.image_url %>)">
        <%= alien.name %>
        <%= link_to alien_path(alien), data: { turbo_method: :delete, turbo_confirm: 'Destroy?'}, class: 'card-remove-link' do %>
          <i class="fa-solid fa-wand-sparkles"></i>
        <% end %>
        <%= link_to new_alien_holster_path(alien), class: 'card-add-link' do %>
          <i class="fa-solid fa-gun"></i>
        <% end %>
        <div class="card-weapons">
          <% alien.weapons.each do |weapon| %>
            <span><%= weapon.name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>